class locators():
    
    #loginpage web_element
    login_username = "//input[@id='username']"
    login_password = "//input[@id='password']"
    login_login_btn = "html/body/div/div/div/form/div[3]/button"
    login_title = "/html/head/title"
    # addlogin web element 
    add_customer_btn_1 = "//*[@id=\"side-menu\"]/li[3]/a"
    add_customer_btn_2 = "//*[@id=\"side-menu\"]/li[3]/ul/li[1]/a"
    add_customer_name = "//*[@id=\"account\"]"
    add_customer_company = "//*[@id=\"cid\"]"
    add_customer_email = "//*[@id=\"email\"]"
    add_customer_phone = "//*[@id=\"phone\"]"
    add_customer_address = "//*[@id=\"address\"]"
    add_customer_city = "//*[@id=\"city\"]"
    add_customer_state = "//*[@id=\"state\"]"
    add_customer_zip = "//*[@id=\"zip\"]"
    add_customer_country = "//*[@id=\"country\"]"
    add_customer_save_btn = "//*[@id=\"submit\"]"
    add_customer_smr = "//*[@id=\"summary\"]"
    add_customer_list_btn = "//*[@id=\"side-menu\"]/li[3]/ul/li[2]/a"
    add_customer_search_box = "//*[@id='foo_filter']"
    add_customer_tableRows ="//*[@id='page-wrapper']/div[3]/div[1]/div/div/div[2]//tbody//tr"
    add_customer_table_before = "//tbody/tr["
    add_customer_table_after =  "]/td[5]"
    add_customer_delete = "]/td[7]/a[@class='btn btn-danger btn-xs cdelete']"
    add_customer_delete_confirmation = "/html/body/div[1]/div/div/div[2]/button[2]"
    add_customer_deletion_message = "//*[@id='page-wrapper']/div[3]/div[1]"